trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - examples/*
      - .gitignore

schedules:
- cron: "0 0 * * *"
  displayName: Daily CI build
  always: true
  branches:
    include:
    - main

jobs:
- job: PowerShellCore
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-18.04'
      mac:
        imageName: 'macos-10.15'
      windows:
        imageName: 'windows-2019'

  pool:
    vmImage: $(imageName)

  steps:
  - task: PowerShell@2
    displayName: Restore
    inputs:
      filePath: 'tools/restore.ps1'
      pwsh: true
    
  - task: PowerShell@2
    displayName: Test
    inputs:
      filePath: 'tools/run-tests.ps1'
      pwsh: true
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "NUnit"
      testResultsFiles: "test/results.xml"

- job: WindowsPowershell
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: PowerShell@2
    displayName: Restore
    inputs:
      filePath: 'tools/restore.ps1'
    
  - task: PowerShell@2
    displayName: Test
    inputs:
      filePath: 'tools/run-tests.ps1'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "NUnit"
      testResultsFiles: "test/results.xml"

  - task: PowerShell@2
    displayName: TestManifest
    inputs:
      targetType: inline
      script: 'Test-ModuleManifest -Path ./FeatureFlags.psd1'
